<a href="https://colab.research.google.com/github/jm19465/CE888/blob/master/Lab_5/my_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
np.set_printoptions(precision = 3)

df = pd.read_csv("https://raw.githubusercontent.com/albanda/CE888/master/lab5-recommender/jester-data-1.csv", delimiter = ",")
df.drop(df.columns[0], axis = 1, inplace = True)

In [0]:
def replace(orig, percentage=0.1):
  new_data = orig.copy()
  rated = np.where(arr!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [0]:
def predict_rating(user_id, item_id):
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)

def train(user_id, item_id, rating, alpha=0.0001):
    prediction_rating = predict_rating(user_id, item_id)
    error =  prediction_rating - rating
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * error * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * error * user_pref_values
    return error

def sgd(iterations=10):
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                if not rating == 99.0:
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        #if (iteration % 100) == 0:
        print(mse)

In [73]:
print(df)

       -7.82   8.79  -9.66  -8.16  -7.52  ...  99.22  -5.63  99.23  99.24  99.25
0       4.08  -0.29   6.36   4.37  -2.38  ...  -2.14   3.06   0.34  -4.32   1.07
1      99.00  99.00  99.00  99.00   9.03  ...  99.00  99.00  99.00  99.00  99.00
2      99.00   8.35  99.00  99.00   1.80  ...  99.00  99.00  99.00  99.00  99.00
3       8.50   4.61  -4.17  -5.39   1.36  ...   1.55   3.11   6.55   1.80   1.60
4      -6.17  -3.54   0.44  -8.50  -7.09  ...  -3.35   0.05  -9.08  -5.05  -3.45
...      ...    ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
24977   0.44   7.43   9.08   2.33   3.20  ...   9.03   6.55   8.69   8.79   7.43
24978   9.13  -8.16   8.59   9.08   0.87  ...  -8.20  -7.23  -8.59   9.13   8.45
24979  99.00  99.00  99.00  99.00  -7.77  ...  99.00  99.00  99.00  99.00  99.00
24980  99.00  99.00  99.00  99.00  -9.71  ...  99.00  99.00  99.00  99.00  99.00
24981   2.43   2.67  -3.98   4.27  -2.28  ...  99.00  99.00  99.00  99.00  99.00

[24982 rows x 100 columns]


In [52]:
arr = df.values
print(arr)

[[ 4.08 -0.29  6.36 ...  0.34 -4.32  1.07]
 [99.   99.   99.   ... 99.   99.   99.  ]
 [99.    8.35 99.   ... 99.   99.   99.  ]
 ...
 [99.   99.   99.   ... 99.   99.   99.  ]
 [99.   99.   99.   ... 99.   99.   99.  ]
 [ 2.43  2.67 -3.98 ... 99.   99.   99.  ]]


In [53]:
new_arr, idx = replace(arr, 0.1)
print(new_arr)

[[ 4.08 -0.29  6.36 ... 99.   -4.32  1.07]
 [99.   99.   99.   ... 99.   99.   99.  ]
 [99.    8.35 99.   ... 99.   99.   99.  ]
 ...
 [99.   99.   99.   ... 99.   99.   99.  ]
 [99.   99.   99.   ... 99.   99.   99.  ]
 [99.    2.67 -3.98 ... 99.   99.   99.  ]]


In [54]:
arr[idx[0][0], idx[1][0]] # ORIGINAL SET

7.38

In [55]:
new_arr[idx[0][0], idx[1][0]] # VALIDATION SET

99.0

In [64]:
n_latent_factors = 3
user_ratings = new_arr[:,:]


latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))
user_ratings


array([[ 4.08, -0.29,  6.36, ..., 99.  , -4.32,  1.07],
       [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
       [99.  ,  8.35, 99.  , ..., 99.  , 99.  , 99.  ],
       ...,
       [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
       [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
       [99.  ,  2.67, -3.98, ..., 99.  , 99.  , 99.  ]])

In [74]:
sgd()

25.85637108331107
25.08000829466745
24.898612200930803
24.74960842647684
24.601788577323166
24.45190641790147
24.299501197663385
24.144524353837618
23.986929294571727
23.82652987486962


In [75]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[0.801, 0.433, 0.392, ..., 0.878, 0.291, 1.233],
       [1.605, 0.862, 0.869, ..., 1.927, 0.597, 2.625],
       [0.813, 0.505, 0.729, ..., 1.099, 0.403, 1.394],
       ...,
       [1.443, 0.839, 0.942, ..., 1.678, 0.607, 2.269],
       [1.104, 0.671, 0.837, ..., 1.323, 0.506, 1.752],
       [1.019, 0.562, 0.521, ..., 1.103, 0.381, 1.549]])

In [0]:
values = [zip(new_arr[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = df.columns

In [77]:
comparison_data

-7.82  ...                       99.25
0       (4.08, 0.8005286678734403)  ...  (1.07, 1.2328623647330903)
1       (99.0, 1.6046591561702788)  ...    (99.0, 2.62507414370547)
2       (99.0, 0.8129365521546901)  ...  (99.0, 1.3944618066316234)
3        (99.0, 1.368505063122635)  ...   (1.6, 2.1281764835981263)
4      (-6.17, 0.1603388168291085)  ...  (-3.45, 0.417731273389477)
...                            ...  ...                         ...
24977   (0.44, 1.2775483503338096)  ...  (7.43, 1.9245039855801813)
24978   (9.13, 0.3897957705105273)  ...  (8.45, 0.7325953047399704)
24979   (99.0, 1.4434482717164756)  ...  (99.0, 2.2690504306800845)
24980   (99.0, 1.1035846004319867)  ...  (99.0, 1.7517592003479003)
24981     (99.0, 1.01941382478799)  ...   (99.0, 1.549301364804639)

[24982 rows x 100 columns]